import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

export function generatePDFReport(dataObj) {
  const { income, borrowed, expenses, totalIncome, totalBorrowed, totalExpenses, netBalance, reportTitle, dateSubtitle } = dataObj;
  
  const doc = new jsPDF();
  
  // Custom Font setup (using helvetica which is built-in but styled modernly)
  doc.setFont("helvetica", "normal");
  
  // Header
  doc.setFillColor(37, 99, 235); // Tailwind blue-600
  doc.rect(0, 0, 210, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text(`Mohan Kumar Store`, 14, 20);
  
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.text(`${reportTitle || 'Financial Report'}`, 14, 28);
  doc.text(`${dateSubtitle}`, 160, 28, { align: 'right' });
  
  // Summary Cards (drawn manually)
  doc.setTextColor(30, 41, 59); // slate-800
  let startY = 55;
  
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Executive Summary", 14, startY);
  startY += 10;
  
  const drawSummaryBox = (x, y, title, amount, colorRGB) => {
    doc.setDrawColor(226, 232, 240); // slate-200
    doc.setFillColor(248, 250, 252); // slate-50
    doc.roundedRect(x, y, 85, 25, 3, 3, 'FD');
    
    doc.setFontSize(10);
    doc.setTextColor(100, 116, 139); // slate-500
    doc.text(title, x + 5, y + 8);
    
    doc.setFontSize(14);
    doc.setTextColor(...colorRGB);
    doc.text(`Rs. ${amount.toLocaleString()}`, x + 5, y + 18);
  };
  
  drawSummaryBox(14, startY, "TOTAL INCOME", totalIncome, [16, 185, 129]); // emerald-500
  drawSummaryBox(110, startY, "TOTAL BORROWED", totalBorrowed, [59, 130, 246]); // blue-500
  
  startY += 30;
  drawSummaryBox(14, startY, "TOTAL EXPENSES", totalExpenses, [239, 68, 68]); // red-500
  drawSummaryBox(110, startY, netBalance >= 0 ? "NET PROFIT" : "NET DEFICIT", Math.abs(netBalance), netBalance >= 0 ? [37, 99, 235] : [239, 68, 68]); 
  
  startY += 40;

  // Modern Table Styling Options
  const modernTableOptions = {
    theme: 'plain',
    styles: {
      font: 'helvetica',
      fontSize: 10,
      cellPadding: 5,
      textColor: [51, 65, 85], // slate-700
    },
    headStyles: {
      fillColor: [241, 245, 249], // slate-100
      textColor: [15, 23, 42], // slate-900
      fontStyle: 'bold',
      lineWidth: 0.1,
      lineColor: [226, 232, 240], // slate-200
    },
    bodyStyles: {
      lineWidth: 0.1,
      lineColor: [226, 232, 240],
    },
    alternateRowStyles: {
      fillColor: [250, 250, 250]
    },
    margin: { top: 20 },
  };

  // Income Table
  if (income.length > 0) {
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42); // slate-900
    doc.setFont("helvetica", "bold");
    doc.text("Income Records", 14, startY);
    
    autoTable(doc, {
      ...modernTableOptions,
      startY: startY + 5,
      head: [['Date', 'Source/Category', 'Amount', 'Note']],
      body: income.map(i => [
        i.date,
        i.source ? `${i.category} (${i.source})` : i.category,
        `Rs. ${i.amount}`,
        i.note || "-"
      ]),
    });
    startY = doc.lastAutoTable.finalY + 20;
  }

  // Borrowed Table
  if (borrowed.length > 0) {
    if (startY > 230) { doc.addPage(); startY = 20; }
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.text("Borrowed Records", 14, startY);
    
    autoTable(doc, {
      ...modernTableOptions,
      startY: startY + 5,
      head: [['Date', 'Customer Name', 'Amount', 'Note']],
      body: borrowed.map(b => [
        b.date,
        b.borrowerName,
        `Rs. ${b.amount}`,
        b.note || "-"
      ]),
    });
    startY = doc.lastAutoTable.finalY + 20;
  }

  // Expenses Table
  if (expenses.length > 0) {
    if (startY > 230) { doc.addPage(); startY = 20; }
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.text("Expense Records", 14, startY);
    
    autoTable(doc, {
      ...modernTableOptions,
      startY: startY + 5,
      head: [['Date', 'Category', 'Amount', 'Note']],
      body: expenses.map(e => [
        e.date,
        e.category,
        `Rs. ${e.amount}`,
        e.note || "-"
      ]),
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184); // slate-400
    doc.text(`Generated by Mohan Kumar Store Manager - Page ${i} of ${pageCount}`, 14, 290);
  }

  const safeTitle = (reportTitle || 'Report').replace(/[^a-z0-9]/gi, '_');
  doc.save(`Mohan_Store_${safeTitle}.pdf`);
}
